// <auto-generated />
namespace Test.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_ArticleID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_ArticleID));
        
        string IMigrationMetadata.Id
        {
            get { return "201709182111000_added_ArticleID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
